plant_data = {
    "data": {
        "care": {
            "attracts": "Bees, Butterflies",
            "care_level": "Easy",
            "cones": False,
            "created_at": "2026-09-27T11:31:43",
            "cuisine": False,
            "drought_tolerant": True,
            "edible_fruit": False,
            "edible_leaf": False,
            "flowering_season": "Autumn, Winter",
            "flowers": True,
            "fruiting_season": None,
            "fruits": False,
            "growth_rate": "Moderate",
            "hardiness_max": 11.0,
            "hardiness_min": 10.0,
            "harvest_method": None,
            "harvest_season": None,
            "id": 2,
            "invasive": False,
            "leaf": True,
            "maintenance": "Low",
            "medicinal": False,
            "pest_susceptibility": "Mealybugs, Spider mites, Scale insects, Root rot",
            "plant_id": 2,
            "propagation": "Stem cuttings, Leaf cuttings",
            "pruning_amount": 25.0,
            "pruning_interval": "As needed",
            "pruning_months": "Spring, Summer",
            "rare": False,
            "salt_tolerant": False,
            "soil_type": "Gritty, well-draining succulent or cactus mix",
            "sunlight_requirement": "Bright indirect light to full sun",
            "thorny": False,
            "tropical": True,
            "updated_at": "2026-09-27T16:01:08",
            "watering": "Allow soil to dry out completely between waterings",
            "watering_benchmark": "2-3",
            "watering_benchmark_unit": "weeks",
        },
        "created_at": "2026-09-27T11:31:29",
        "id": 2,
        "name": "Kleinia petraea",
        "scientific_name": "Kleinia petraea",
        "updated_at": "2026-09-27T11:31:29",
    },
    "extracted_raw": {
        "attracts": "Bees, Butterflies",
        "care_level": "Easy",
        "cones": False,
        "cuisine": False,
        "drought_tolerant": True,
        "edible_fruit": False,
        "edible_leaf": False,
        "flowering_season": "Autumn, Winter",
        "flowers": True,
        "fruiting_season": None,
        "fruits": False,
        "growth_rate": "Moderate",
        "hardiness_max": 11.0,
        "hardiness_min": 10.0,
        "harvest_method": None,
        "harvest_season": None,
        "invasive": False,
        "leaf": True,
        "maintenance": "Low",
        "medicinal": False,
        "pest_susceptibility": "Mealybugs, Spider mites, Scale insects, Root rot",
        "propagation": "Stem cuttings, Leaf cuttings",
        "pruning_amount": 25.0,
        "pruning_interval": "As needed",
        "pruning_months": "Spring, Summer",
        "rare": False,
        "salt_tolerant": False,
        "soil_type": "Gritty, well-draining succulent or cactus mix",
        "sunlight_requirement": "Bright indirect light to full sun",
        "thorny": False,
        "tropical": True,
        "watering": "Allow soil to dry out completely between waterings",
        "watering_benchmark": "2-3",
        "watering_benchmark_unit": "weeks",
    },
    "message": "Care data successfully extracted and persisted to database",
    "status": "success",
}
