"""changing previous table structure.

Revision ID: 36999845a3d5
Revises: 
Create Date: 2026-08-19 20:32:36.067483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36999845a3d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scientific_name', sa.String(length=300), nullable=True),
    sa.Column('common_name', sa.String(length=300), nullable=True),
    sa.Column('image_url', sa.String(length=600), nullable=True),
    sa.Column('family', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pet_toxicity_level', sa.String(length=50), nullable=True),
    sa.Column('human_toxicity_level', sa.String(length=50), nullable=True),
    sa.Column('pet_toxicity_description', sa.Text(), nullable=True),
    sa.Column('human_toxicity_description', sa.Text(), nullable=True),
    sa.Column('medicinal_uses', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scientific_name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('plant_care',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('sunlight_requirement', sa.String(length=300), nullable=True),
    sa.Column('watering_frequency', sa.Integer(), nullable=True),
    sa.Column('watering_unit', sa.String(length=30), nullable=True),
    sa.Column('soil_type', sa.String(length=300), nullable=True),
    sa.Column('min_temp', sa.Float(), nullable=True),
    sa.Column('max_temp', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('image_path', sa.String(length=600), nullable=False),
    sa.Column('identified_name', sa.String(length=300), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('identification_status', sa.String(length=50), nullable=True),
    sa.Column('scan_timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scan_history')
    op.drop_table('plant_care')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('plant')
    # ### end Alembic commands ###
