"""Fix(DB): Rest the entire database structure.

Revision ID: e637a3b326b3
Revises: 
Create Date: 2026-09-26 09:28:15.377719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e637a3b326b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scientific_name', sa.String(length=300), nullable=True),
    sa.Column('common_name', sa.String(length=300), nullable=True),
    sa.Column('image_url', sa.String(length=600), nullable=True),
    sa.Column('family', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pet_toxicity_level', sa.String(length=50), nullable=True),
    sa.Column('human_toxicity_level', sa.String(length=50), nullable=True),
    sa.Column('pet_toxicity_description', sa.Text(), nullable=True),
    sa.Column('human_toxicity_description', sa.Text(), nullable=True),
    sa.Column('medicinal_uses', sa.Text(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('perenual_species_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scientific_name')
    )
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plant_perenual_species_id'), ['perenual_species_id'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('plant_care',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('watering', sa.String(length=50), nullable=True),
    sa.Column('watering_benchmark', sa.String(length=50), nullable=True),
    sa.Column('watering_benchmark_unit', sa.String(length=30), nullable=True),
    sa.Column('sunlight_requirement', sa.Text(), nullable=True),
    sa.Column('soil_type', sa.Text(), nullable=True),
    sa.Column('hardiness_min', sa.Float(), nullable=True),
    sa.Column('hardiness_max', sa.Float(), nullable=True),
    sa.Column('pruning_months', sa.Text(), nullable=True),
    sa.Column('pruning_amount', sa.Float(), nullable=True),
    sa.Column('pruning_interval', sa.String(length=50), nullable=True),
    sa.Column('propagation', sa.Text(), nullable=True),
    sa.Column('attracts', sa.Text(), nullable=True),
    sa.Column('pest_susceptibility', sa.Text(), nullable=True),
    sa.Column('flowering_season', sa.String(length=100), nullable=True),
    sa.Column('fruiting_season', sa.String(length=100), nullable=True),
    sa.Column('harvest_season', sa.String(length=100), nullable=True),
    sa.Column('harvest_method', sa.String(length=100), nullable=True),
    sa.Column('growth_rate', sa.String(length=50), nullable=True),
    sa.Column('maintenance', sa.String(length=50), nullable=True),
    sa.Column('care_level', sa.String(length=50), nullable=True),
    sa.Column('flowers', sa.Boolean(), nullable=True),
    sa.Column('cones', sa.Boolean(), nullable=True),
    sa.Column('fruits', sa.Boolean(), nullable=True),
    sa.Column('leaf', sa.Boolean(), nullable=True),
    sa.Column('edible_fruit', sa.Boolean(), nullable=True),
    sa.Column('edible_leaf', sa.Boolean(), nullable=True),
    sa.Column('medicinal', sa.Boolean(), nullable=True),
    sa.Column('drought_tolerant', sa.Boolean(), nullable=True),
    sa.Column('salt_tolerant', sa.Boolean(), nullable=True),
    sa.Column('thorny', sa.Boolean(), nullable=True),
    sa.Column('invasive', sa.Boolean(), nullable=True),
    sa.Column('rare', sa.Boolean(), nullable=True),
    sa.Column('tropical', sa.Boolean(), nullable=True),
    sa.Column('cuisine', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plant_id')
    )
    op.create_table('scan_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('image_path', sa.String(length=600), nullable=False),
    sa.Column('identified_name', sa.String(length=300), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('identification_status', sa.String(length=50), nullable=True),
    sa.Column('scan_timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scan_history')
    op.drop_table('plant_care')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plant_perenual_species_id'))

    op.drop_table('plant')
    # ### end Alembic commands ###
